name: Test Project
on: push
jobs:
  test:
    #node already installed on ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3 #uses keyword --> To use a defined action, v3 is the version
      - name: Install nodejs
        #to install a specific nodejs version, remember node is installed in the runner, see comment in line 5
        uses: actions/setup-node@v3
          with: 
            node-version: 18
      - name: Install dependencies
        run: npm ci
      - name:  Run tests
        run: npm test
